---
  - name: Update timezone
    become: yes
    become_method: sudo
    script: dpkg-reconfigure/tzdata.sh

  - name: Disable ssh password authentication
    become: yes
    become_method: sudo
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "^#PasswordAuthentication"
      line: "PasswordAuthentication no"
      backrefs: yes
      state: present
    notify: Restart ssh

  - name: Make sde directory
    file:
      path: "/home/{{ username }}/sde"
      owner: "{{ username }}"
      group: "{{ username }}"
      state: directory

  - name: Install some useful packages
    become: yes
    become_method: sudo
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - htop
      - tmux
      - man-db
      - python3-pip

  - name: Install some necessary pip packages
    pip:
      name: "{{ packages }}"
    vars:
      packages:
      - click_logging
      - cmakeast

  - name: Add hugepages configuration
    become: yes
    become_method: sudo
    sysctl:
      name: vm.nr_hugepages
      value: '128'
      reload: yes

  - name: Update ~/.profile
    blockinfile:
      path: /home/{{ username }}/.profile
      block: |
        export SDE="/home/{{ username }}/sde/bf-sde-9.13.0"
        export SDE_INSTALL="/home/{{ username }}/sde/bf-sde-9.13.0/install"
        export PATH="$PATH:$SDE_INSTALL/bin"


  - name: Update ~/.bashrc
    lineinfile:
      dest: /home/{{ username }}/.bashrc
      regexp: "^#alias ll='ls -l'"
      line: "alias ll='ls -l'"
      backrefs: yes
      state: present

  - name: Copy bf-sde
    copy:
      src: sde/bf-sde-9.11.2.tgz
      dest: /home/{{ username }}/sde/bf-sde-9.13.0.tgz
      owner: "{{ username }}"
      group: "{{ username }}"
      mode: '0755'

  - name: Copy aps-bsp
    copy:
      src: sde/bf-reference-bsp-9.11.2.tgz
      dest: /home/{{ username }}/sde/bf-reference-bsp-9.13.0.tgz
      owner: "{{ username }}"
      group: "{{ username }}"
      mode: '0755'


  - name: Copy ska config yaml
    copy:
      src: sde/ska.yaml
      dest: /home/{{ username }}/sde/ska.yaml
      owner: "{{ username }}"
      group: "{{ username }}"
      mode: '0644'

  - name: Extract SDE file
    unarchive:
      src: /home/{{ username }}/sde/bf-sde-9.13.0.tgz
      dest: /home/{{ username }}/sde/
      remote_src: yes

  - name: compile SDE
    ansible.builtin.shell: ./p4studio profile apply /home/{{ username }}/sde/ska.yaml
    args:
      chdir: /home/{{ username }}/sde/bf-sde-9.11.2/p4studio/
